on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: volta-cli/action@v1
    - name: Install Dependencies
      run: yarn install
    - name: Run ESLint
      run: yarn lint:js -f tap

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ember-try-scenario: [ember-default, ember-lts-3.12, ember-lts-3.16, ember-release, ember-beta, ember-canary, ember-classic]
    steps:
    - uses: actions/checkout@v1
    - uses: volta-cli/action@v1
    - name: Install Dependencies
      run: yarn install
    - name: Run Tests
      run: yarn ember try:one ${{ matrix.ember-try-scenario }}
      env:
        CI: true


